### ISSUE TITLE
这个EFI我能直接导入就能用吗，和显示器DP DVI HDMI 用什么口有关系吗？

### ISSUE THREAD

**Issue by DeckardCainCN** [kuaima/Dell-OptiPlex-7050-Clover-EFI#1]

**Comment by kuaima** [comment]
正好补充些信息
我手头的机器有2个DP口，一个HDMI口，其中靠近中间的DP口+HDMI口可以正常使用，靠外的DP口在启动阶段可用，但是进入macOS之后不可用，HDMI口黑屏后，需要重新启动显示器的电源开关才可以激活，不过影响不大，可以正常使用。
