### ISSUE TITLE
OptiPlex5050 安装完成启动的时候黑屏只有鼠标

### ISSUE THREAD

**Issue by amesshen** [kuaima/Dell-OptiPlex-7050-Clover-EFI#5]
你好，OptiPlex5050 安装完成启动的时候一直黑屏，只有鼠标可见。
请问我需要做什么调整吗，折腾好几天了，求救求救：）

**Comment by kuaima** [comment]
可以看看你的5050的机器是啥配置，主要是CPU和GPU，clover里对应的机型可能需要调整，
还有几个排查点：
- BIOS中有些配置需要关闭，主要是security boot 和虚拟机相关的地方
- 安装的过程到哪一步了？看看能不能抓出日志来

**Comment by kuaima** [comment]
另外，还有一个参考的地方，这套配置只是在10.15.7上跑通，更高的版本没尝试过

**Comment by amesshen** [comment]
> 另外，还有一个参考的地方，这套配置只是在10.15.7上跑通，更高的版本没尝试过

谢谢大佬解答。
我用的是10.15.5，然后CPU是i5-7500，GPU是集显630，没有独显。
由于是工作机，又改成win10先干活了，等下一个空闲期我再用10.15.7安装试试。再次感谢大佬
